import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { SyncioDatabase, createSyncioServer, ReplicationClient, ChangeLog, createReplicationPacket, applyReplicatedChange, migrate } from '../src/index.js';

async function database(name){const root=await fs.mkdtemp(path.join(os.tmpdir(),`syncio-${name}-`));const file=path.join(root,'db.json');return{file,db:await SyncioDatabase.open(file)};}
const allowAll=[{effect:'allow'}];

test('serialized persistence survives 50 concurrent writers and clean restart',async()=>{const {file,db}=await database('concurrent');const collection=db.collection('items');await Promise.all(Array.from({length:50},(_,i)=>collection.insert({id:`r${i}`,value:i})));await db.close();const reopened=await SyncioDatabase.open(file);assert.equal(reopened.collection('items').all().length,50);for(let i=0;i<50;i++)assert.equal(reopened.collection('items').get(`r${i}`).value,i);});

test('failed duplicate mutation does not corrupt durable state or later write queue',async()=>{const {file,db}=await database('failure');const collection=db.collection('items');await collection.insert({id:'same',value:1});await assert.rejects(collection.insert({id:'same',value:2}),/already exists/);await collection.insert({id:'after',value:3});await db.close();const disk=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(disk.collections.items.same.value,1);assert.equal(disk.collections.items.after.value,3);});

test('two self-hosted nodes exchange replicated records over real HTTP and persist them',async(t)=>{const a=await database('node-a'),b=await database('node-b');const serverA=createSyncioServer({db:a.db,policies:allowAll,nodeId:'node-a'});const serverB=createSyncioServer({db:b.db,policies:allowAll,nodeId:'node-b'});t.after(()=>Promise.all([serverA.close(),serverB.close()]));const addressA=await serverA.listen(),addressB=await serverB.listen();await fetch(`${addressA.url}/collections/items/one`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({value:'from-a',updatedAt:'2026-08-14T00:00:00Z'})});const pull=new ReplicationClient({baseUrl:addressA.url,nodeId:'bridge'});const count=await pull.pull(async(change)=>{const packet=createReplicationPacket({from:'bridge',changes:[change]});const response=await fetch(`${addressB.url}/replicate/push`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(packet)});assert.equal(response.status,200);});assert.equal(count,1);assert.equal(b.db.collection('items').get('one').value,'from-a');await b.db.close();const reopened=await SyncioDatabase.open(b.file);assert.equal(reopened.collection('items').get('one').value,'from-a');});

test('offline client retains failed queue then reconnects and flushes exactly once',async(t)=>{const state=await database('reconnect');const service=createSyncioServer({db:state.db,policies:allowAll,nodeId:'server'});let online=false;let address;const fetchImpl=async(...args)=>{if(!online)throw new Error('offline');return fetch(...args);};const client=new ReplicationClient({baseUrl:'http://127.0.0.1:1',nodeId:'client',fetchImpl});client.queue({collection:'items',type:'upsert',record:{id:'offline',value:7,updatedAt:new Date().toISOString()}});let flush=await client.flush();assert.equal(flush.pending,1);address=await service.listen();t.after(()=>service.close());client.baseUrl=address.url;online=true;flush=await client.flush();assert.equal(flush.pending,0);assert.equal(state.db.collection('items').get('offline').value,7);});

test('conflict storm converges deterministically under last-write-wins regardless of arrival order',async()=>{const changes=[];for(let i=0;i<100;i++)changes.push({collection:'items',type:'upsert',record:{id:'same',value:i,updatedAt:new Date(1700000000000+i*1000).toISOString()}});const left=await database('conflict-left'),right=await database('conflict-right');for(const change of changes)await applyReplicatedChange(left.db,change);for(const change of [...changes].reverse())await applyReplicatedChange(right.db,change);assert.deepEqual(left.db.collection('items').get('same'),right.db.collection('items').get('same'));assert.equal(left.db.collection('items').get('same').value,99);});

test('authorization denies reads writes and replication when no policy permits them',async(t)=>{const state=await database('policy');const service=createSyncioServer({db:state.db,policies:[],nodeId:'deny'});const address=await service.listen();t.after(()=>service.close());let response=await fetch(`${address.url}/collections/items`);assert.equal(response.status,403);response=await fetch(`${address.url}/collections/items/x`,{method:'PUT',headers:{'content-type':'application/json'},body:'{"value":1}'});assert.equal(response.status,403);response=await fetch(`${address.url}/replicate/pull`,{method:'POST',headers:{'content-type':'application/json'},body:'{"cursor":0}'});assert.equal(response.status,403);});

test('real stored snapshot migrates through ordered versions without mutating migration registry',async()=>{const source={version:1,collections:{users:{u1:{id:'u1',name:'Charles'}}}};const migrations=[{version:3,up:(state)=>{state.collections.users.u1.active=true;return state;}},{version:2,up:(state)=>{state.collections.users.u1.name=state.collections.users.u1.name.toUpperCase();return state;}}];const originalOrder=migrations.map(m=>m.version);const migrated=migrate(source,migrations);assert.equal(migrated.version,3);assert.equal(migrated.collections.users.u1.name,'CHARLES');assert.equal(migrated.collections.users.u1.active,true);assert.deepEqual(migrations.map(m=>m.version),originalOrder);assert.equal(source.version,1);});
