import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { StorageBackedSyncioDatabase } from '../src/storage-core.js';

async function temp(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'syncio-storage-core-'));return{root,file:path.join(root,'data.syncio.json')};}

test('storage core makes segmented state authoritative and survives restart',async(t)=>{const s=await temp();t.after(()=>fs.rm(s.root,{recursive:true,force:true}));let db=await StorageBackedSyncioDatabase.open(s.file,{checkpointEvery:1000,storage:{cacheBytes:1024*1024}});await db.collection('items').upsert({id:'a',value:1});const status=db.storageStatus();assert.equal(status.authoritativeState,'ssd-segments');assert.equal(status.fullStateResidentInRam,false);assert.ok(status.walEntries>=1);await db.close();db=await StorageBackedSyncioDatabase.open(s.file);assert.equal(db.collection('items').get('a').value,1);await db.close();});

test('one durable transaction produces one Commit Fabric identity across its mutations',async(t)=>{const s=await temp();t.after(()=>fs.rm(s.root,{recursive:true,force:true}));const db=await StorageBackedSyncioDatabase.open(s.file);const events=[];db.watchChanges({after:0},e=>events.push(e));await db.transaction(tx=>{tx.collection('items').put({id:'a',value:1});tx.collection('items').put({id:'b',value:2});});assert.equal(events.length,2);assert.equal(events[0].commitId,events[1].commitId);assert.equal(events[0].transactionId,events[1].transactionId);assert.match(events[0].commitChecksum,/^[a-f0-9]{64}$/);await db.close();});

test('OCC retries a transaction when a record changes during an async read/write window',async(t)=>{const s=await temp();t.after(()=>fs.rm(s.root,{recursive:true,force:true}));const db=await StorageBackedSyncioDatabase.open(s.file);await db.collection('counters').upsert({id:'n',value:0});let release;const gate=new Promise(r=>{release=r;});let first=true,attempts=0;const slow=db.transaction(async tx=>{attempts++;const c=tx.collection('counters'),r=c.get('n');if(first){first=false;await gate;}c.put({...r,value:r.value+1});});await new Promise(r=>setImmediate(r));await db.collection('counters').upsert({id:'n',value:10});release();await slow;assert.equal(db.collection('counters').get('n').value,11);assert.ok(attempts>=2);await db.close();});

test('reactive query subscriptions only publish relevant committed query changes',async(t)=>{const s=await temp();t.after(()=>fs.rm(s.root,{recursive:true,force:true}));const db=await StorageBackedSyncioDatabase.open(s.file);await db.collection('orders').upsert({id:'a',status:'open',note:'x'});const received=[];const stop=db.subscribeQuery('orders',{where:{status:'open'}},event=>received.push(event));await new Promise(r=>setImmediate(r));await db.collection('other').upsert({id:'z',value:1});await db.collection('orders').upsert({id:'a',status:'closed',note:'x'});await new Promise(r=>setImmediate(r));assert.equal(received[0].initial,true);assert.deepEqual(received.at(-1).value,[]);assert.equal(received.length,2);stop();await db.close();});

test('offline transaction intent survives database restart and reconciles through real transaction engine',async(t)=>{const s=await temp();t.after(()=>fs.rm(s.root,{recursive:true,force:true}));let db=await StorageBackedSyncioDatabase.open(s.file);await db.collection('accounts').upsert({id:'a',balance:5});await db.enqueueOfflineIntent({intentId:'intent-1',preconditions:[{collection:'accounts',id:'a',equals:{id:'a',balance:5}}],mutation:{type:'put',collection:'accounts',record:{id:'a',balance:9}},conflictPolicy:'reject'});await db.close();db=await StorageBackedSyncioDatabase.open(s.file);assert.equal(db.listOfflineIntents().find(x=>x.intentId==='intent-1').status,'pending');const results=await db.reconcileOfflineIntents();assert.equal(results[0].status,'committed');assert.equal(db.collection('accounts').get('a').balance,9);await db.close();});

test('legacy checkpoint migrates into segmented authoritative state without data loss',async(t)=>{const s=await temp();t.after(()=>fs.rm(s.root,{recursive:true,force:true}));await fs.writeFile(s.file,JSON.stringify({version:1,databaseId:'legacy-db',sequence:3,collections:{items:{a:{id:'a',value:7}}},changes:[],appliedChangeIds:[]}));const db=await StorageBackedSyncioDatabase.open(s.file);assert.equal(db.databaseId,'legacy-db');assert.equal(db.sequence,3);assert.equal(db.collection('items').get('a').value,7);assert.equal(db.lastRecoveryManifest().failure,'legacy_state_migration');await db.close();});
