import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createCommitFabric,verifyCommitFabric} from '../src/commit-fabric.js';import {ReactiveQueryGraph} from '../src/reactive.js';import {SyncView,DurableIntentLog} from '../src/sync-plane.js';import {AdaptiveScheduler,PRIORITY} from '../src/scheduler.js';import {CONSISTENCY,consistencyContract} from '../src/consistency.js';import {createRecoveryManifest,verifyRecoveryManifest} from '../src/recovery-manifest.js';import {compilePolicy,differentialPolicyCheck} from '../src/policy-compiler.js';import {LocalityAdvisor} from '../src/locality.js';

test('commit fabric is tamper evident',()=>{const c=createCommitFabric({databaseId:'db',sequence:1,mutations:[{collection:'x',id:'1'}]});assert.equal(verifyCommitFabric(c),true);assert.equal(verifyCommitFabric({...c,sequence:2}),false);});
test('reactive graph only invalidates relevant fields',async()=>{let n=0;const g=new ReactiveQueryGraph();g.register('q',{collection:'users',query:{name:'a'},evaluate:async()=>++n});let r=await g.applyCommit({commitId:'1',mutations:[{collection:'users',fields:['age']}]});assert.equal(r.length,0);r=await g.applyCommit({commitId:'2',mutations:[{collection:'users',fields:['name']}]});assert.equal(r.length,1);});
test('sync views bound expansion and durable intents survive restart',async()=>{const v=new SyncView({collection:'x',predicate:r=>r.ok,maxDocuments:1});assert.deepEqual(v.select([{id:'1',ok:true}]),[{id:'1',ok:true}]);assert.throws(()=>v.select([{id:'1',ok:true},{id:'2',ok:true}]));const dir=await fs.mkdtemp(path.join(os.tmpdir(),'syncio-intent-'));const file=path.join(dir,'intents.json');let log=await DurableIntentLog.open(file);const i=await log.enqueue({mutation:{type:'put',record:{id:'1'}}});log=await DurableIntentLog.open(file);assert.equal(log.list()[0].intentId,i.intentId);await fs.rm(dir,{recursive:true,force:true});});
test('scheduler protects budgets and correctness',()=>{const s=new AdaptiveScheduler({budgets:{cpu:1}});assert.equal(s.admit({cost:{cpu:1},priority:PRIORITY.foreground}).decision,'admit');assert.equal(s.admit({cost:{cpu:1},priority:PRIORITY.foreground}).decision,'reject');assert.equal(s.admit({cost:{cpu:1},priority:PRIORITY.correctness}).decision,'defer');});
test('consistency contracts are explicit',()=>{assert.equal(consistencyContract(CONSISTENCY.SERIALIZABLE).serializable,true);assert.equal(consistencyContract(CONSISTENCY.EVENTUAL).allowsStaleReads,true);});
test('recovery manifests are verifiable',()=>{const m=createRecoveryManifest({finalSequence:8,invariants:['wal-valid']});assert.equal(verifyRecoveryManifest(m),true);assert.equal(verifyRecoveryManifest({...m,finalSequence:9}),false);});
test('compiled policy agrees with reference',()=>{const p={actions:['read'],tenant:'a',where:{owner:'u'}};const c=compilePolicy(p);assert.equal(c.evaluate({action:'read',tenant:'a',resource:{owner:'u'}}),true);assert.equal(differentialPolicyCheck(p,[{action:'read',tenant:'a',resource:{owner:'u'}},{action:'write',tenant:'a',resource:{owner:'u'}}]).ok,true);});
test('locality advisor identifies hotspots',()=>{const a=new LocalityAdvisor();for(let i=0;i<10;i++)a.observe(['p1']);assert.equal(a.report().recommendation,'rebalance_or_refine_affinity');});
