export const PRIORITY=Object.freeze({durability:100,correctness:90,foreground:80,replication:70,realtime:60,index:40,background:20});

export class AdaptiveScheduler {
  constructor({budgets={},mode='balanced',parent=null,name='root'}={}){this.budgets={cpu:Infinity,memory:Infinity,ssdIo:Infinity,network:Infinity,egress:Infinity,coordination:Infinity,...budgets};this.mode=mode;this.parent=parent;this.name=name;this.used={};this.metrics={admitted:0,rejected:0,deferred:0,completed:0};this.children=new Map();}
  estimate(task){const c={cpu:0,memory:0,ssdIo:0,network:0,egress:0,coordination:0,recoveryRisk:0,latency:0,...task.cost};const weights=this.mode==='cost'?{egress:5,cpu:2,memory:2,ssdIo:1,network:3,coordination:2,recoveryRisk:4,latency:1}:this.mode==='latency'?{egress:1,cpu:1,memory:1,ssdIo:2,network:3,coordination:3,recoveryRisk:4,latency:6}:{egress:2,cpu:2,memory:2,ssdIo:2,network:2,coordination:2,recoveryRisk:4,latency:3};return{cost:c,score:Object.entries(c).reduce((n,[k,v])=>n+(weights[k]??1)*v,0)};}
  child(name,{budgets={},mode=this.mode}={}){if(typeof name!=='string'||!name)throw new TypeError('scheduler child name required');if(this.children.has(name))return this.children.get(name);const child=new AdaptiveScheduler({budgets,mode,parent:this,name:`${this.name}/${name}`});this.children.set(name,child);return child;}
  admit(task){const {cost,score}=this.estimate(task);const exceeded=exceeds(this.budgets,this.used,cost);if(exceeded.length)return this.#refuse(task,exceeded,score);let parentAdmission=null;if(this.parent){parentAdmission=this.parent.admit({...task,cost});if(parentAdmission.decision!=='admit')return parentAdmission;}for(const[k,v]of Object.entries(cost))this.used[k]=(this.used[k]??0)+v;this.metrics.admitted++;let released=false;return{decision:'admit',score,scheduler:this.name,release:()=>{if(released)return;released=true;for(const[k,v]of Object.entries(cost))this.used[k]=Math.max(0,(this.used[k]??0)-v);parentAdmission?.release?.();this.metrics.completed++;}};}
  async run(task,work){if(typeof work!=='function')throw new TypeError('scheduled work function required');const admission=this.admit(task);if(admission.decision!=='admit'){const e=new Error(`scheduler ${admission.decision}`);e.code=admission.decision==='defer'?'SYNCIO_RESOURCE_DEFERRED':'SYNCIO_RESOURCE_BUSY';e.details=admission;throw e;}try{return await work();}finally{admission.release();}}
  #refuse(task,exceeded,score){if((task.priority??0)>=PRIORITY.correctness){this.metrics.deferred++;return{decision:'defer',exceeded,score,scheduler:this.name};}this.metrics.rejected++;return{decision:'reject',exceeded,score,scheduler:this.name};}
  choose(candidates,{objective=this.mode}={}){if(!Array.isArray(candidates)||!candidates.length)throw new TypeError('execution candidates required');return candidates.map(candidate=>({...candidate,estimate:this.estimate({cost:candidate.cost??{}})})).sort((a,b)=>a.estimate.score-b.estimate.score||String(a.id).localeCompare(String(b.id)))[0];}
  snapshot(){return{mode:this.mode,name:this.name,budgets:{...this.budgets},used:{...this.used},metrics:{...this.metrics},children:Object.fromEntries([...this.children].map(([k,v])=>[k,v.snapshot()]))};}
}

export class ExecutionCostModel {
  constructor({cpuPerMs=0.000001,memoryPerByteMs=0.000000000001,ssdPerByte=0.00000000002,networkPerByte=0.00000000008,egressPerByte=0.00000000012,coordination=0.00001}={}){this.rates={cpuPerMs,memoryPerByteMs,ssdPerByte,networkPerByte,egressPerByte,coordination};this.observations=new Map();}
  observe(kind,{latencyMs=0,cpuMs=0,memoryBytes=0,ssdBytes=0,networkBytes=0,egressBytes=0,coordinationOps=0}={}){const current=this.observations.get(kind)??{count:0,latencyMs:0,cpuMs:0,memoryBytes:0,ssdBytes:0,networkBytes:0,egressBytes:0,coordinationOps:0};current.count++;for(const key of Object.keys(current))if(key!=='count')current[key]+=Number(arguments[1]?.[key]??0);this.observations.set(kind,current);return this.average(kind);}
  average(kind){const x=this.observations.get(kind);if(!x)return null;const out={count:x.count};for(const[k,v]of Object.entries(x))if(k!=='count')out[k]=v/x.count;out.economicCost=this.cost(out);return out;}
  cost(x){return (x.cpuMs??0)*this.rates.cpuPerMs+(x.memoryBytes??0)*(x.latencyMs??0)*this.rates.memoryPerByteMs+(x.ssdBytes??0)*this.rates.ssdPerByte+(x.networkBytes??0)*this.rates.networkPerByte+(x.egressBytes??0)*this.rates.egressPerByte+(x.coordinationOps??0)*this.rates.coordination;}
  choose(candidates){if(!Array.isArray(candidates)||!candidates.length)throw new TypeError('cost candidates required');return candidates.map(c=>({...c,economicCost:this.cost(c.metrics??c)})).sort((a,b)=>a.economicCost-b.economicCost||String(a.id).localeCompare(String(b.id)))[0];}
  snapshot(){return{rates:{...this.rates},observations:Object.fromEntries([...this.observations].map(([k])=>[k,this.average(k)]))};}
}

export function planTransfer({deltaBytes,snapshotBytes,roundTrips=1,networkCostPerByte=1,coordinationCost=4096}={}){for(const v of [deltaBytes,snapshotBytes])if(!Number.isFinite(v)||v<0)throw new TypeError('transfer bytes must be non-negative');const deltaCost=deltaBytes*networkCostPerByte+roundTrips*coordinationCost;const snapshotCost=snapshotBytes*networkCostPerByte+coordinationCost;return deltaCost<=snapshotCost?{strategy:'delta',cost:deltaCost}:{strategy:'snapshot',cost:snapshotCost};}

function exceeds(budgets,used,cost){return Object.entries(budgets).filter(([k,max])=>(used[k]??0)+(cost[k]??0)>max).map(([k])=>k);}
