import crypto from 'node:crypto';
import path from 'node:path';
import fs from 'node:fs/promises';
import { queryRecords } from './advanced.js';
import { DurablePartitionParticipant, DurableTransactionCoordinator } from './distributed.js';
import { ExecutionCostModel } from './scheduler.js';

export class ConsistentHashRing {
  constructor(shardIds,{virtualNodes=128}={}){if(!Array.isArray(shardIds)||shardIds.length<1||new Set(shardIds).size!==shardIds.length)throw new TypeError('unique shardIds required');if(!Number.isSafeInteger(virtualNodes)||virtualNodes<1||virtualNodes>4096)throw new TypeError('virtualNodes must be between 1 and 4096');this.shardIds=[...shardIds].sort();this.virtualNodes=virtualNodes;this.points=[];for(const shardId of this.shardIds){if(typeof shardId!=='string'||!shardId)throw new TypeError('shard id must be non-empty string');for(let i=0;i<virtualNodes;i++)this.points.push({hash:hash32(`${shardId}:${i}`),shardId});}this.points.sort((a,b)=>a.hash-b.hash||a.shardId.localeCompare(b.shardId));}
  locate(key){if(typeof key!=='string'||!key)throw new TypeError('shard key must be non-empty string');const hash=hash32(key);let low=0,high=this.points.length;while(low<high){const mid=(low+high)>>1;if(this.points[mid].hash<hash)low=mid+1;else high=mid;}return this.points[low===this.points.length?0:low].shardId;}
  distribution(keys){const counts=Object.fromEntries(this.shardIds.map(id=>[id,0]));for(const key of keys)counts[this.locate(String(key))]++;return counts;}
}

export class ShardedSyncioDatabase {
  constructor(shards,{virtualNodes=128,shardKey='id',costModel=new ExecutionCostModel(),coordinator=null,participants=null}={}){if(!shards||typeof shards!=='object'||Array.isArray(shards))throw new TypeError('shards object required');const entries=Object.entries(shards);if(!entries.length)throw new TypeError('at least one shard required');for(const[id,db]of entries)if(!db||typeof db.collection!=='function'||typeof db.transaction!=='function')throw new TypeError(`invalid database for shard ${id}`);this.shards=new Map(entries);this.ring=new ConsistentHashRing([...this.shards.keys()],{virtualNodes});this.shardKey=shardKey;this.costModel=costModel;this.coordinator=coordinator;this.participants=participants;this.metrics={targetedQueries:0,scatterQueries:0,distributedTransactions:0,reservationRejects:0};}
  static async open(shards,{journalDirectory,virtualNodes=128,shardKey='id',costModel}={}){const db=new ShardedSyncioDatabase(shards,{virtualNodes,shardKey,costModel});if(journalDirectory){const root=path.resolve(journalDirectory);await fs.mkdir(root,{recursive:true});const participants={};for(const[id,shard]of db.shards)participants[id]=await DurablePartitionParticipant.open(id,shard,path.join(root,`participant-${encodeURIComponent(id)}.json`));db.participants=participants;db.coordinator=await DurableTransactionCoordinator.open(path.join(root,'coordinator.json'),participants);await db.coordinator.recover();}return db;}
  get shardIds(){return[...this.shards.keys()].sort();}
  locate(value){return this.ring.locate(extractShardKey(value,this.shardKey));}
  shard(id){const db=this.shards.get(id);if(!db)throw new Error(`unknown shard ${id}`);return db;}
  guard(shardId,mutation){try{return this.participants?.[shardId]?.guardMutation(mutation)??true;}catch(error){this.metrics.reservationRejects++;throw error;}}
  collection(name){const router=this;return Object.freeze({
    async insert(value){const record={...value,id:value?.id??crypto.randomUUID()},shardId=router.locate(record);router.guard(shardId,{type:'put',collection:name,record});return router.shard(shardId).collection(name).insert(record);},
    async upsert(value){if(!value?.id)throw new TypeError('sharded upsert requires id');const shardId=router.locate(value);router.guard(shardId,{type:'put',collection:name,record:value});return router.shard(shardId).collection(name).upsert(value);},
    get(id,shardValue=id){return router.shard(router.locate(typeof shardValue==='object'?shardValue:{id:String(shardValue)})).collection(name).get(id);},
    async remove(id,shardValue=id){const shardId=router.locate(typeof shardValue==='object'?shardValue:{id:String(shardValue)});router.guard(shardId,{type:'remove',collection:name,id});return router.shard(shardId).collection(name).remove(id);},
    all(){return router.shardIds.flatMap(id=>router.shard(id).collection(name).all());},
    query(spec={}){return router.queryCollection(name,spec);}
  });}
  queryCollection(name,spec={}){const target=this.queryTarget(spec);if(target){this.metrics.targetedQueries++;return this.shard(target).collection(name).query?.(spec)??queryRecords(this.shard(target).collection(name).all(),spec);}this.metrics.scatterQueries++;const candidates=this.shardIds.map(id=>({id,metrics:{networkBytes:1024,coordinationOps:1,latencyMs:1},records:this.shard(id).collection(name).all()}));const ordered=[...candidates].sort((a,b)=>this.costModel.cost(a.metrics)-this.costModel.cost(b.metrics)||a.id.localeCompare(b.id));return queryRecords(ordered.flatMap(x=>x.records),spec);}
  queryTarget(spec){const where=spec?.where;if(!where||typeof where!=='object'||Array.isArray(where))return null;const value=Object.hasOwn(where,this.shardKey)?where[this.shardKey]:readPath(where,this.shardKey);if(value===undefined||value===null||typeof value==='object')return null;return this.locate(setPath({},this.shardKey,value));}
  explainQuery(spec={}){const target=this.queryTarget(spec);return target?{strategy:'targeted_shard',shard:target}:{strategy:'scatter_gather',shards:this.shardIds};}
  async transaction(shardValue,work){if(typeof work!=='function')throw new TypeError('sharded transaction requires work callback');const shardId=this.locate(typeof shardValue==='object'?shardValue:{id:String(shardValue)});if(this.participants?.[shardId]?.unresolved().length)throw shardError('SYNCIO_DISTRIBUTED_LOCKED','shard has prepared distributed transaction');return this.shard(shardId).transaction(work);}
  async distributedTransaction(plan,options={}){if(!this.coordinator)throw shardError('SYNCIO_DISTRIBUTED_COORDINATOR_REQUIRED','open sharded database with journalDirectory to enable distributed transactions');this.metrics.distributedTransactions++;return this.coordinator.execute(plan,options);}
  async distributedMutate(mutations,options={}){if(!Array.isArray(mutations)||!mutations.length)throw new TypeError('distributed mutations required');const plan={};for(const mutation of mutations){if(!mutation?.collection)throw new TypeError('mutation collection required');const value=mutation.record??{id:mutation.id};const shardId=this.locate(value);(plan[shardId]??=[]).push(mutation);}if(Object.keys(plan).length===1){const[[shardId,ops]]=Object.entries(plan);for(const op of ops)this.guard(shardId,op);const result=await this.shard(shardId).transaction(tx=>{for(const op of ops)applyMutation(tx,op);});return{status:'committed',local:true,shards:[shardId],result};}return this.distributedTransaction(plan,options);}
  async recoverDistributedTransactions(){if(!this.coordinator)return[];return this.coordinator.recover();}
  async moveRecord(collection,id,{fromShard,toShard,verify=true}={}){const source=this.shard(fromShard),target=this.shard(toShard);if(fromShard===toShard)return{moved:false,reason:'same_shard'};this.guard(fromShard,{type:'remove',collection,id});const record=source.collection(collection).get(id);if(!record)return{moved:false,reason:'not_found'};this.guard(toShard,{type:'put',collection,record});await target.collection(collection).upsert(record);if(verify){const copied=target.collection(collection).get(id);if(JSON.stringify(copied)!==JSON.stringify(record)){await target.collection(collection).remove(id).catch(()=>undefined);throw shardError('SYNCIO_SHARD_VERIFY_FAILED','target verification failed');}}await source.collection(collection).remove(id);return{moved:true,id,fromShard,toShard};}
  async rebalanceCollection(collection,{dryRun=false,limit=Infinity}={}){if(!(Number.isFinite(limit)||limit===Infinity)||limit<1)throw new TypeError('rebalance limit must be positive');const moves=[];for(const fromShard of this.shardIds){for(const record of this.shard(fromShard).collection(collection).all()){const toShard=this.locate(record);if(toShard!==fromShard){moves.push({id:record.id,fromShard,toShard});if(moves.length>=limit)break;}}if(moves.length>=limit)break;}if(!dryRun)for(const move of moves)await this.moveRecord(collection,move.id,move);return{planned:moves.length,moved:dryRun?0:moves.length,moves};}
  status(){return{shards:this.shardIds,metrics:{...this.metrics},distributedTransactions:Boolean(this.coordinator),costModel:this.costModel.snapshot()};}
  async close(){await Promise.all(this.shardIds.map(id=>this.shard(id).close()));}
}

export function planShardMigration(records,currentShard,nextShardIds,{virtualNodes=128,shardKey='id'}={}){const ring=new ConsistentHashRing(nextShardIds,{virtualNodes});return records.map(record=>({id:record.id,fromShard:currentShard,toShard:ring.locate(extractShardKey(record,shardKey))})).filter(item=>item.fromShard!==item.toShard);}
function applyMutation(tx,m){const c=tx.collection(m.collection);if(m.type==='remove')return c.remove(m.id);if(['put','upsert','insert'].includes(m.type))return c.put(m.record);throw new TypeError('unsupported distributed mutation');}
function extractShardKey(value,field){if(typeof value==='string')return value;if(!value||typeof value!=='object')throw new TypeError('record or shard key required');const current=Object.hasOwn(value,field)?value[field]:readPath(value,field);if(current===undefined||current===null||current==='')throw new TypeError(`missing shard key ${field}`);return String(current);}
function readPath(value,field){let current=value;for(const part of String(field).split('.'))current=current?.[part];return current;}
function setPath(target,field,value){const parts=String(field).split('.');let current=target;for(let i=0;i<parts.length-1;i++)current=current[parts[i]]={};current[parts.at(-1)]=value;return target;}
function hash32(value){const digest=crypto.createHash('sha256').update(value).digest();return digest.readUInt32BE(0);}
function shardError(code,message){const error=new Error(message);error.code=code;return error;}
