import fsSync from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { StorageBackedSyncioDatabase } from './storage-core.js';
import { queryRecords } from './advanced.js';
import { firstPathValue } from './document.js';

const clone=(v)=>structuredClone(v);

export class SuperiorIndexedSyncioDatabase {
  constructor(base,catalogFile,definitions={},options={}){this.base=base;this.file=base.file;this.catalogFile=catalogFile;this.indexRoot=path.resolve(`${base.file}.secondary-indexes`);this.definitions=normalizeDefinitions(definitions);this.indexes=new Map();this.catalogQueue=Promise.resolve();this.indexCacheBuckets=options.indexCacheBuckets??64;}
  static async open(file,options={}){const base=await StorageBackedSyncioDatabase.open(file,options);const catalogFile=path.resolve(`${base.file}.indexes.json`);let definitions={};try{definitions=JSON.parse(await fs.readFile(catalogFile,'utf8')).indexes??{};}catch(e){if(e.code!=='ENOENT'){await base.close();throw e;}}const db=new SuperiorIndexedSyncioDatabase(base,catalogFile,definitions,options);try{await db.initializeIndexes();return db;}catch(error){await base.close();throw error;}}
  get databaseId(){return this.base.databaseId;}get sequence(){return this.base.sequence;}
  storageStatus(){return{...this.base.storageStatus(),indexes:this.listIndexes().length,secondaryIndexes:Object.fromEntries([...this.indexes].map(([k,v])=>[k,v.stats()]))};}
  resumeStatus(c){return this.base.resumeStatus(c);}watchChanges(o,l){return this.base.watchChanges(o,l);}watchCommits(l){return this.base.watchCommits(l);}consistency(...a){return this.base.consistency(...a);}

  async initializeIndexes(){await fs.mkdir(this.indexRoot,{recursive:true});for(const[collection,defs]of Object.entries(this.definitions))for(const definition of defs){const index=await PersistentDocumentIndex.open(this.indexDirectory(collection,definition.name),definition,{maxCachedBuckets:this.indexCacheBuckets});this.indexes.set(indexKey(collection,definition.name),index);await this.catchUpIndex(collection,index);}}
  async catchUpIndex(collection,index){if(index.sequence===this.sequence)return;if(index.sequence>this.sequence){await index.rebuild(this.base.collection(collection).scan(),this.sequence);return;}const resume=this.base.resumeStatus(index.sequence);if(!resume.resumable){await index.rebuild(this.base.collection(collection).scan(),this.sequence);return;}const changes=this.base.changesSince(index.sequence).filter(e=>e.collection===collection);for(const event of changes)await index.apply(event.before??null,event.record??null,event.sequence);if(index.sequence!==this.sequence)await index.setSequence(this.sequence);}

  async defineIndex(collection,fields,options={}){validateName(collection,'collection');const normalizedFields=normalizeFields(fields);const definition=normalizeDefinition({name:options.name??normalizedFields.join('_'),fields:normalizedFields,unique:options.unique===true,sparse:options.sparse===true});const current=this.definitions[collection]??[],collision=current.find(x=>x.name===definition.name);if(collision&&!sameDefinition(collision,definition))throw indexError('SYNCIO_INDEX_NAME_CONFLICT','index name conflict');if(collision)return publicDefinition(collection,collision);const index=await PersistentDocumentIndex.open(this.indexDirectory(collection,definition.name),definition,{maxCachedBuckets:this.indexCacheBuckets});await index.rebuild(this.base.collection(collection).scan(),this.sequence);this.definitions={...this.definitions,[collection]:[...current,definition]};this.indexes.set(indexKey(collection,definition.name),index);await this.persistCatalog();return publicDefinition(collection,definition);}
  async dropIndex(collection,nameOrFields){const name=Array.isArray(nameOrFields)?normalizeFields(nameOrFields).join('_'):String(nameOrFields),current=this.definitions[collection]??[],target=current.find(x=>x.name===name||(x.fields.length===1&&x.fields[0]===name));if(!target)return false;const nextDefs=current.filter(x=>x!==target),next={...this.definitions};if(nextDefs.length)next[collection]=nextDefs;else delete next[collection];this.definitions=next;this.indexes.delete(indexKey(collection,target.name));await fs.rm(this.indexDirectory(collection,target.name),{recursive:true,force:true});await this.persistCatalog();return true;}
  listIndexes(){return Object.entries(this.definitions).flatMap(([c,defs])=>defs.map(d=>publicDefinition(c,d)));}

  collection(name){const db=this;return Object.freeze({
    async insert(value){const record={...value,id:value?.id??crypto.randomUUID()};await db.transaction(tx=>{const c=tx.collection(name);if(c.get(record.id))throw indexError('SYNCIO_DUPLICATE_ID','duplicate id');c.put(record);});return clone(record);},
    async upsert(value){await db.transaction(tx=>tx.collection(name).put(value));return clone(value);},
    get:id=>db.base.collection(name).get(id),all(){const records=db.base.collection(name).all();Object.defineProperty(records,'__syncioQuery',{value:spec=>db.query(name,spec),enumerable:false});return records;},scan:()=>db.base.collection(name).scan(),query:spec=>db.query(name,spec),explain:spec=>db.explainQuery(name,spec),
    async remove(id){let removed=false;await db.transaction(tx=>{removed=tx.collection(name).remove(id);});return removed;},watch:l=>db.base.collection(name).watch(l)
  });}

  query(collection,spec={}){const plan=this.explainQuery(collection,spec);if(plan.strategy==='index'){const index=this.indexes.get(indexKey(collection,plan.index));if(index){const records=index.find(plan.values).map(id=>this.base.collection(collection).get(id)).filter(Boolean);return queryRecords(records,spec);}}return queryRecords(this.base.collection(collection).all(),spec);}
  explainQuery(collection,spec={}){const where=spec.where&&typeof spec.where==='object'&&!Array.isArray(spec.where)?spec.where:{};const candidates=(this.definitions[collection]??[]).filter(d=>d.fields.every(f=>simpleEquality(where[f]))).sort((a,b)=>b.fields.length-a.fields.length);const best=candidates[0];return best?{strategy:'index',index:best.name,fields:[...best.fields],values:best.fields.map(f=>where[f])}:{strategy:'scan'};}

  async transaction(work,options={}){const start=this.sequence;const result=await this.base.transaction(tx=>work(this.transactionProxy(tx)),options);await this.applyCommittedIndexChanges(start);return result;}
  transactionProxy(tx){const db=this;return Object.freeze({readVersion:tx.readVersion,collection(name){const c=tx.collection(name);return Object.freeze({get:id=>c.get(id),all:()=>c.all(),put(record){if(!record?.id)throw new TypeError('transaction put requires id');db.assertUnique(name,record,record.id);return c.put(record);},remove:id=>c.remove(id)});}});}
  assertUnique(collection,candidate,excludeId){for(const d of this.definitions[collection]??[]){if(!d.unique)continue;const values=d.fields.map(f=>firstPathValue(candidate,f));if(d.sparse&&values.some(v=>v===undefined))continue;const index=this.indexes.get(indexKey(collection,d.name));for(const id of index?.find(values)??[])if(id!==excludeId)throw indexError('SYNCIO_UNIQUE_INDEX_VIOLATION',`unique index '${d.name}' rejected duplicate value`);}}
  async applyCommittedIndexChanges(after){for(const event of this.base.changesSince(after)){for(const definition of this.definitions[event.collection]??[]){const index=this.indexes.get(indexKey(event.collection,definition.name));if(index)await index.apply(event.before??null,event.record??null,event.sequence);}}for(const index of this.indexes.values())if(index.sequence<this.sequence)await index.setSequence(this.sequence);}

  changesSince(...a){return this.base.changesSince(...a);}hasAppliedChange(...a){return this.base.hasAppliedChange(...a);}snapshot(){return this.base.snapshot();}checkpoint(){return this.base.checkpoint();}
  async replaceState(s){const result=await this.base.replaceState(s);for(const[collection,defs]of Object.entries(this.definitions))for(const definition of defs){const index=this.indexes.get(indexKey(collection,definition.name));await index.rebuild(this.base.collection(collection).scan(),this.sequence);}return result;}
  async applyReplicationChange(change,resolver){const start=this.sequence;const wrapped=(local,remote)=>{const resolved=resolver(local,remote);if(resolved)this.assertUnique(change.collection,resolved,resolved.id);return resolved;};const result=await this.base.applyReplicationChange(change,wrapped);if(result.applied)await this.applyCommittedIndexChanges(start);return result;}
  subscribeQuery(collection,spec,listener,options){return this.base.subscribeQuery(collection,spec,listener,options);}defineSyncView(...a){return this.base.defineSyncView(...a);}materializeSyncView(...a){return this.base.materializeSyncView(...a);}syncViewChanges(...a){return this.base.syncViewChanges(...a);}enqueueOfflineIntent(...a){return this.base.enqueueOfflineIntent(...a);}listOfflineIntents(){return this.base.listOfflineIntents();}reconcileOfflineIntents(){return this.base.reconcileOfflineIntents();}lastRecoveryManifest(){return this.base.lastRecoveryManifest();}
  async close(){await this.catalogQueue;for(const index of this.indexes.values())await index.close();await this.base.close();}
  indexDirectory(collection,name){return path.join(this.indexRoot,encodeURIComponent(collection),encodeURIComponent(name));}
  persistCatalog(){const op=this.catalogQueue.then(()=>atomicJson(this.catalogFile,{version:3,indexes:this.definitions}));this.catalogQueue=op.catch(()=>undefined);return op;}
}

class PersistentDocumentIndex {
  constructor(directory,definition,state,{maxCachedBuckets}){this.directory=directory;this.definition=definition;this.manifestFile=path.join(directory,'manifest.json');this.bucketDir=path.join(directory,'buckets');this.sequence=state.sequence??0;this.maxCachedBuckets=maxCachedBuckets;this.cache=new Map();this.hits=0;this.misses=0;this.evictions=0;this.queue=Promise.resolve();}
  static async open(directory,definition,{maxCachedBuckets=64}={}){await fs.mkdir(path.join(directory,'buckets'),{recursive:true});let state={version:1,sequence:0,definition:publicDiskDefinition(definition)};try{state=JSON.parse(await fs.readFile(path.join(directory,'manifest.json'),'utf8'));}catch(error){if(error.code!=='ENOENT')throw error;}if(state.version!==1||stableKey(state.definition)!==stableKey(publicDiskDefinition(definition)))state={version:1,sequence:0,definition:publicDiskDefinition(definition)};const index=new PersistentDocumentIndex(directory,definition,state,{maxCachedBuckets});if(!(await exists(index.manifestFile)))await index.persistManifest();return index;}
  find(values){if(this.definition.sparse&&values.some(v=>v===undefined))return[];const key=stableKey(values),bucket=this.loadBucket(bucketName(key));return[...(bucket.entries[key]??[])];}
  async rebuild(records,sequence){return this.#enqueue(async()=>{await fs.rm(this.bucketDir,{recursive:true,force:true});await fs.mkdir(this.bucketDir,{recursive:true});this.cache.clear();const dirty=new Map();for(const record of records){const changed=this.addToBucket(record,dirty);if(this.definition.unique&&changed.conflict)throw indexError('SYNCIO_UNIQUE_INDEX_VIOLATION',`unique index '${this.definition.name}' contains duplicate value`);}for(const bucket of dirty.values())await this.persistBucket(bucket);this.sequence=sequence;await this.persistManifest();return this;});}
  async apply(before,after,sequence){return this.#enqueue(async()=>{const dirty=new Map();if(before)this.removeFromBucket(before,dirty);if(after){const changed=this.addToBucket(after,dirty);if(this.definition.unique&&changed.conflict)throw indexError('SYNCIO_UNIQUE_INDEX_VIOLATION',`unique index '${this.definition.name}' contains duplicate value`);}for(const bucket of dirty.values())await this.persistBucket(bucket);this.sequence=Math.max(this.sequence,sequence??this.sequence);await this.persistManifest();});}
  async setSequence(sequence){this.sequence=sequence;await this.persistManifest();}
  addToBucket(record,dirty){const values=this.definition.fields.map(f=>firstPathValue(record,f));if(this.definition.sparse&&values.some(v=>v===undefined))return{conflict:false};const key=stableKey(values),name=bucketName(key),bucket=dirty.get(name)??this.loadBucket(name),ids=new Set(bucket.entries[key]??[]);const conflict=this.definition.unique&&ids.size>0&&!ids.has(record.id);ids.add(record.id);bucket.entries[key]=[...ids].sort();dirty.set(name,bucket);return{conflict};}
  removeFromBucket(record,dirty){const values=this.definition.fields.map(f=>firstPathValue(record,f));if(this.definition.sparse&&values.some(v=>v===undefined))return;const key=stableKey(values),name=bucketName(key),bucket=dirty.get(name)??this.loadBucket(name),ids=new Set(bucket.entries[key]??[]);ids.delete(record.id);if(ids.size)bucket.entries[key]=[...ids].sort();else delete bucket.entries[key];dirty.set(name,bucket);}
  loadBucket(name){const cached=this.cache.get(name);if(cached){this.hits++;this.cache.delete(name);this.cache.set(name,cached);return cached;}this.misses++;let bucket={version:1,name,entries:{}};try{bucket=JSON.parse(fsSync.readFileSync(path.join(this.bucketDir,`${name}.json`),'utf8'));}catch(error){if(error.code!=='ENOENT')throw indexError('SYNCIO_INDEX_CORRUPT',`index bucket read failed: ${error.message}`);}if(bucket.version!==1||!bucket.entries||typeof bucket.entries!=='object')throw indexError('SYNCIO_INDEX_CORRUPT','invalid index bucket');this.cache.set(name,bucket);while(this.cache.size>this.maxCachedBuckets){const oldest=this.cache.keys().next().value;this.cache.delete(oldest);this.evictions++;}return bucket;}
  async persistBucket(bucket){await atomicJson(path.join(this.bucketDir,`${bucket.name}.json`),bucket);this.cache.delete(bucket.name);this.cache.set(bucket.name,bucket);}
  async persistManifest(){await atomicJson(this.manifestFile,{version:1,sequence:this.sequence,definition:publicDiskDefinition(this.definition)});}
  stats(){return{format:'persistent-secondary-index/1',sequence:this.sequence,cachedBuckets:this.cache.size,maxCachedBuckets:this.maxCachedBuckets,hits:this.hits,misses:this.misses,evictions:this.evictions};}
  async close(){await this.queue;this.cache.clear();}
  #enqueue(fn){const op=this.queue.then(fn);this.queue=op.catch(()=>undefined);return op;}
}

function normalizeDefinitions(v){if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('invalid index catalog');const out={};for(const[c,raw]of Object.entries(v)){validateName(c,'collection');if(!Array.isArray(raw))throw new Error('invalid index definitions');out[c]=raw.map(x=>typeof x==='string'?normalizeDefinition({name:x,fields:[x]}):normalizeDefinition(x));}return out;}
function normalizeDefinition(d){const fields=normalizeFields(d.fields??d.field),name=d.name??fields.join('_');validateName(name,'name');return Object.freeze({name,fields,unique:d.unique===true,sparse:d.sparse===true});}
function normalizeFields(v){const a=typeof v==='string'?[v]:v;if(!Array.isArray(a)||!a.length||a.length>16)throw new TypeError('index fields require 1-16 fields');const out=a.map(x=>{validateName(x,'field');return x;});if(new Set(out).size!==out.length)throw new TypeError('index fields unique');return out;}
function publicDefinition(c,d){return d.fields.length===1&&!d.unique&&!d.sparse&&d.name===d.fields[0]?{collection:c,field:d.fields[0]}:{collection:c,name:d.name,fields:[...d.fields],unique:d.unique,sparse:d.sparse};}
function publicDiskDefinition(d){return{name:d.name,fields:[...d.fields],unique:d.unique,sparse:d.sparse};}
function simpleEquality(v){return v!==undefined&&!(v&&typeof v==='object'&&!Array.isArray(v));}
function sameDefinition(a,b){return a.name===b.name&&a.unique===b.unique&&a.sparse===b.sparse&&stableKey(a.fields)===stableKey(b.fields);}
function stableKey(values){return canonical(values);}
function canonical(v){if(v===undefined)return'u';if(v===null)return'n';if(typeof v==='string')return`s:${JSON.stringify(v)}`;if(typeof v==='number')return`d:${Object.is(v,-0)?'-0':String(v)}`;if(typeof v==='boolean')return`b:${v?1:0}`;if(Array.isArray(v))return`a:[${v.map(canonical).join(',')}]`;if(typeof v==='object')return`o:{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return`${typeof v}:${String(v)}`;}
function bucketName(key){return crypto.createHash('sha256').update(key).digest('hex').slice(0,4);}
function indexKey(c,n){return`${c}\u0000${n}`;}
function validateName(v,l){if(typeof v!=='string'||!/^[A-Za-z0-9_.-]+$/.test(v)||v.length>128)throw new TypeError(`invalid index ${l}`);}
function indexError(code,message){const e=new Error(message);e.code=code;e.statusCode=code==='SYNCIO_UNIQUE_INDEX_VIOLATION'?409:500;return e;}
async function exists(file){try{await fs.access(file);return true;}catch{return false;}}
async function atomicJson(file,value){await fs.mkdir(path.dirname(file),{recursive:true});const temp=`${file}.${crypto.randomUUID()}.tmp`;try{await fs.writeFile(temp,`${JSON.stringify(value)}\n`,{mode:0o600});const h=await fs.open(temp,'r');try{await h.sync();}finally{await h.close();}await fs.rename(temp,file);const d=await fs.open(path.dirname(file),'r');try{await d.sync();}finally{await d.close();}}finally{await fs.rm(temp,{force:true}).catch(()=>undefined);}}
