import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { StorageBackedSyncioDatabase } from './storage-core.js';
import { queryRecords } from './advanced.js';
import { firstPathValue } from './document.js';

export class SuperiorIndexedSyncioDatabase {
  constructor(base,catalogFile,definitions={}){this.base=base;this.file=base.file;this.catalogFile=catalogFile;this.definitions=normalizeDefinitions(definitions);this.indexes=new Map();this.catalogQueue=Promise.resolve();this.rebuildAll();}
  static async open(file,options={}){const base=await StorageBackedSyncioDatabase.open(file,options);const catalogFile=path.resolve(`${base.file}.indexes.json`);let definitions={};try{definitions=JSON.parse(await fs.readFile(catalogFile,'utf8')).indexes??{};}catch(e){if(e.code!=='ENOENT')throw e;}return new SuperiorIndexedSyncioDatabase(base,catalogFile,definitions);}
  get databaseId(){return this.base.databaseId;}get sequence(){return this.base.sequence;}storageStatus(){return{...this.base.storageStatus(),indexes:this.listIndexes().length};}resumeStatus(c){return this.base.resumeStatus(c);}watchChanges(o,l){return this.base.watchChanges(o,l);}watchCommits(l){return this.base.watchCommits(l);}consistency(...a){return this.base.consistency(...a);}

  async defineIndex(collection,fields,options={}){validateName(collection,'collection');const normalizedFields=normalizeFields(fields);const definition=normalizeDefinition({name:options.name??normalizedFields.join('_'),fields:normalizedFields,unique:options.unique===true,sparse:options.sparse===true});const current=this.definitions[collection]??[],collision=current.find(x=>x.name===definition.name);if(collision&&!sameDefinition(collision,definition))throw indexError('SYNCIO_INDEX_NAME_CONFLICT','index name conflict');if(collision)return publicDefinition(collection,collision);const index=new DocumentIndex(definition).rebuild(this.base.collection(collection).all());this.definitions={...this.definitions,[collection]:[...current,definition]};this.indexes.set(indexKey(collection,definition.name),index);await this.persistCatalog();return publicDefinition(collection,definition);}
  async dropIndex(collection,nameOrFields){const name=Array.isArray(nameOrFields)?normalizeFields(nameOrFields).join('_'):String(nameOrFields),current=this.definitions[collection]??[],nextDefs=current.filter(x=>x.name!==name&&!(x.fields.length===1&&x.fields[0]===name));if(nextDefs.length===current.length)return false;const next={...this.definitions};if(nextDefs.length)next[collection]=nextDefs;else delete next[collection];this.definitions=next;this.rebuildCollection(collection);await this.persistCatalog();return true;}
  listIndexes(){return Object.entries(this.definitions).flatMap(([c,defs])=>defs.map(d=>publicDefinition(c,d)));}

  collection(name){const db=this;return Object.freeze({
    async insert(value){const record={...value,id:value?.id??crypto.randomUUID()};await db.transaction(tx=>{const c=tx.collection(name);if(c.get(record.id))throw indexError('SYNCIO_DUPLICATE_ID','duplicate id');c.put(record);});return structuredClone(record);},
    async upsert(value){await db.transaction(tx=>tx.collection(name).put(value));return structuredClone(value);},
    get:id=>db.base.collection(name).get(id),all(){const records=db.base.collection(name).all();Object.defineProperty(records,'__syncioQuery',{value:spec=>db.query(name,spec),enumerable:false});return records;},scan:()=>db.base.collection(name).scan(),query:spec=>db.query(name,spec),explain:spec=>db.explainQuery(name,spec),
    async remove(id){let removed=false;await db.transaction(tx=>{removed=tx.collection(name).remove(id);});return removed;},watch:l=>db.base.collection(name).watch(l)
  });}

  query(collection,spec={}){const plan=this.explainQuery(collection,spec);if(plan.strategy==='index'){const index=this.indexes.get(indexKey(collection,plan.index));if(index){const records=index.find(plan.values).map(id=>this.base.collection(collection).get(id)).filter(Boolean);return queryRecords(records,spec);}}return queryRecords(this.base.collection(collection).all(),spec);}
  explainQuery(collection,spec={}){const where=spec.where&&typeof spec.where==='object'&&!Array.isArray(spec.where)?spec.where:{};const candidates=(this.definitions[collection]??[]).filter(d=>d.fields.every(f=>simpleEquality(where[f]))).sort((a,b)=>b.fields.length-a.fields.length);const best=candidates[0];return best?{strategy:'index',index:best.name,fields:[...best.fields],values:best.fields.map(f=>where[f])}:{strategy:'scan'};}

  async transaction(work,options={}){const touched=new Set();const result=await this.base.transaction(tx=>work(this.transactionProxy(tx,touched)),options);for(const name of touched)this.rebuildCollection(name);return result;}
  transactionProxy(tx,touched){const db=this;return Object.freeze({readVersion:tx.readVersion,collection(name){const c=tx.collection(name);return Object.freeze({get:id=>c.get(id),all:()=>c.all(),put(record){if(!record?.id)throw new TypeError('transaction put requires id');db.assertUnique(name,record,record.id,c.all());c.put(record);touched.add(name);},remove(id){const r=c.remove(id);if(r)touched.add(name);return r;}});}});}
  assertUnique(collection,candidate,excludeId,records){for(const d of this.definitions[collection]??[]){if(!d.unique)continue;const values=d.fields.map(f=>firstPathValue(candidate,f));if(d.sparse&&values.some(v=>v===undefined))continue;for(const r of records){if(r.id===excludeId)continue;const existing=d.fields.map(f=>firstPathValue(r,f));if(stableKey(values)===stableKey(existing))throw indexError('SYNCIO_UNIQUE_INDEX_VIOLATION',`unique index '${d.name}' rejected duplicate value`);}}}

  changesSince(...a){return this.base.changesSince(...a);}hasAppliedChange(...a){return this.base.hasAppliedChange(...a);}snapshot(){return this.base.snapshot();}checkpoint(){return this.base.checkpoint();}replaceState(s){return this.base.replaceState(s).then(r=>{this.rebuildAll();return r;});}
  async applyReplicationChange(change,resolver){const wrapped=(local,remote)=>{const resolved=resolver(local,remote);if(resolved)this.assertUnique(change.collection,resolved,resolved.id,this.base.collection(change.collection).all());return resolved;};const result=await this.base.applyReplicationChange(change,wrapped);if(result.applied)this.rebuildCollection(change.collection);return result;}
  subscribeQuery(collection,spec,listener,options){return this.base.subscribeQuery(collection,spec,listener,options);}defineSyncView(...a){return this.base.defineSyncView(...a);}materializeSyncView(...a){return this.base.materializeSyncView(...a);}enqueueOfflineIntent(...a){return this.base.enqueueOfflineIntent(...a);}listOfflineIntents(){return this.base.listOfflineIntents();}reconcileOfflineIntents(){return this.base.reconcileOfflineIntents();}lastRecoveryManifest(){return this.base.lastRecoveryManifest();}
  async close(){await this.catalogQueue;await this.base.close();}

  rebuildCollection(collection){for(const k of [...this.indexes.keys()])if(k.startsWith(`${collection}\u0000`))this.indexes.delete(k);const records=this.base.collection(collection).all();for(const d of this.definitions[collection]??[])this.indexes.set(indexKey(collection,d.name),new DocumentIndex(d).rebuild(records));}
  rebuildAll(){this.indexes.clear();for(const c of Object.keys(this.definitions))this.rebuildCollection(c);}
  persistCatalog(){const op=this.catalogQueue.then(()=>atomicJson(this.catalogFile,{version:2,indexes:this.definitions}));this.catalogQueue=op.catch(()=>undefined);return op;}
}

class DocumentIndex{constructor(definition){this.definition=definition;this.map=new Map();}rebuild(records){this.map.clear();for(const r of records)this.add(r);return this;}add(record){const values=this.definition.fields.map(f=>firstPathValue(record,f));if(this.definition.sparse&&values.some(v=>v===undefined))return;const key=stableKey(values),set=this.map.get(key)??new Set();if(this.definition.unique&&set.size&&!set.has(record.id))throw indexError('SYNCIO_UNIQUE_INDEX_VIOLATION',`unique index '${this.definition.name}' contains duplicate value`);set.add(record.id);this.map.set(key,set);}find(values){return[...(this.map.get(stableKey(values))??[])];}}
function normalizeDefinitions(v){if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('invalid index catalog');const out={};for(const[c,raw]of Object.entries(v)){validateName(c,'collection');if(!Array.isArray(raw))throw new Error('invalid index definitions');out[c]=raw.map(x=>typeof x==='string'?normalizeDefinition({name:x,fields:[x]}):normalizeDefinition(x));}return out;}
function normalizeDefinition(d){const fields=normalizeFields(d.fields??d.field),name=d.name??fields.join('_');validateName(name,'name');return Object.freeze({name,fields,unique:d.unique===true,sparse:d.sparse===true});}
function normalizeFields(v){const a=typeof v==='string'?[v]:v;if(!Array.isArray(a)||!a.length||a.length>16)throw new TypeError('index fields require 1-16 fields');const out=a.map(x=>{validateName(x,'field');return x;});if(new Set(out).size!==out.length)throw new TypeError('index fields unique');return out;}
function publicDefinition(c,d){return d.fields.length===1&&!d.unique&&!d.sparse&&d.name===d.fields[0]?{collection:c,field:d.fields[0]}:{collection:c,name:d.name,fields:[...d.fields],unique:d.unique,sparse:d.sparse};}
function simpleEquality(v){return v!==undefined&&!(v&&typeof v==='object'&&!Array.isArray(v));}function sameDefinition(a,b){return a.name===b.name&&a.unique===b.unique&&a.sparse===b.sparse&&stableKey(a.fields)===stableKey(b.fields);}function stableKey(v){return JSON.stringify(v);}function indexKey(c,n){return`${c}\u0000${n}`;}function validateName(v,l){if(typeof v!=='string'||!/^[A-Za-z0-9_.-]+$/.test(v)||v.length>128)throw new TypeError(`invalid index ${l}`);}function indexError(code,message){const e=new Error(message);e.code=code;e.statusCode=409;return e;}
async function atomicJson(file,value){await fs.mkdir(path.dirname(file),{recursive:true});const temp=`${file}.${crypto.randomUUID()}.tmp`;try{await fs.writeFile(temp,`${JSON.stringify(value,null,2)}\n`,{mode:0o600});const h=await fs.open(temp,'r');try{await h.sync();}finally{await h.close();}await fs.rename(temp,file);const d=await fs.open(path.dirname(file),'r');try{await d.sync();}finally{await d.close();}}finally{await fs.rm(temp,{force:true}).catch(()=>undefined);}}
