import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';

const clone=(value)=>structuredClone(value);

export class SyncView {
  constructor({collection,predicate=()=>true,maxDocuments=100000}){if(typeof collection!=='string'||!collection)throw new TypeError('sync view collection required');if(typeof predicate!=='function')throw new TypeError('sync view predicate required');if(!Number.isSafeInteger(maxDocuments)||maxDocuments<1)throw new TypeError('maxDocuments must be positive');this.collection=collection;this.predicate=predicate;this.maxDocuments=maxDocuments;}
  select(records,context={}){const selected=[];for(const record of records){if(this.predicate(record,context)){selected.push(clone(record));if(selected.length>this.maxDocuments)throw limit('sync view expansion limit exceeded');}}return selected;}
}

export class DurableIntentLog {
  constructor(file,state){this.file=path.resolve(file);this.state=state;this.queue=Promise.resolve();}
  static async open(file){const target=path.resolve(file);let state=freshState();try{state=JSON.parse(await fs.readFile(target,'utf8'));verifyState(state);}catch(error){if(error.code!=='ENOENT')throw error;}return new DurableIntentLog(target,state);}
  list(){return Object.values(this.state.intents).map((intent)=>clone(intent)).sort((a,b)=>a.createdAt-b.createdAt||a.intentId.localeCompare(b.intentId));}
  get(intentId){const value=this.state.intents[intentId];return value?clone(value):null;}
  async enqueue(intent){validateIntent(intent);const intentId=intent.intentId??crypto.randomUUID();if(this.state.intents[intentId])return clone(this.state.intents[intentId]);const mutations=normalizeMutations(intent);const normalized={version:1,intentId,createdAt:Date.now(),status:'pending',preconditions:clone(intent.preconditions??[]),readAssumptions:clone(intent.readAssumptions??[]),mutations,conflictPolicy:intent.conflictPolicy??'reject',expiresAt:intent.expiresAt??null,retryPolicy:normalizeRetry(intent.retryPolicy),origin:intent.origin??'client',attempts:0,lastError:null,updatedAt:Date.now()};this.state.intents[intentId]=normalized;await this.persist();return clone(normalized);}
  async cancel(intentId){const live=this.state.intents[intentId];if(!live)return false;if(live.status==='committed')throw intentError('SYNCIO_INTENT_ALREADY_COMMITTED','committed intent cannot be cancelled');live.status='cancelled';live.updatedAt=Date.now();await this.persist();return true;}
  async reconcile(executor,{now=Date.now()}={}){if(typeof executor!=='function')throw new TypeError('intent executor required');const results=[];for(const intent of this.list().filter((item)=>item.status==='pending')){const live=this.state.intents[intent.intentId];if(intent.expiresAt&&intent.expiresAt<=now){live.status='expired';live.updatedAt=now;results.push({intentId:intent.intentId,status:'expired'});continue;}try{const result=await executor(intent);live.status=result?.status??'committed';live.attempts++;live.lastError=null;live.updatedAt=now;results.push({intentId:intent.intentId,...result,status:live.status});}catch(error){live.attempts++;live.lastError=error.code??'execution_failed';live.updatedAt=now;if(error.code==='SYNCIO_INTENT_CONFLICT'){live.status='conflict';}else if(live.attempts>=live.retryPolicy.maxAttempts){live.status='failed';}results.push({intentId:intent.intentId,status:live.status,error:live.lastError});}}await this.persist();return results;}
  async retry(intentId){const live=this.state.intents[intentId];if(!live)throw intentError('SYNCIO_INTENT_NOT_FOUND','intent not found');if(!['conflict','failed'].includes(live.status))throw intentError('SYNCIO_INTENT_NOT_RETRYABLE','intent is not retryable');live.status='pending';live.lastError=null;live.updatedAt=Date.now();await this.persist();return clone(live);}
  async prune({before=Date.now(),statuses=['committed','expired','cancelled']}={}){const allowed=new Set(statuses);let removed=0;for(const[intentId,intent]of Object.entries(this.state.intents)){if(allowed.has(intent.status)&&(intent.updatedAt??intent.createdAt)<=before){delete this.state.intents[intentId];removed++;}}if(removed)await this.persist();return removed;}
  async close(){await this.queue;}
  async persist(){const snapshot={version:1,intents:this.state.intents,checksum:stateChecksum(this.state.intents)};this.state=snapshot;const operation=this.queue.then(async()=>{await fs.mkdir(path.dirname(this.file),{recursive:true});const tmp=`${this.file}.${crypto.randomUUID()}.tmp`;try{await fs.writeFile(tmp,`${JSON.stringify(snapshot)}\n`,{mode:0o600});const handle=await fs.open(tmp,'r');try{await handle.sync();}finally{await handle.close();}await fs.rename(tmp,this.file);const directory=await fs.open(path.dirname(this.file),'r');try{await directory.sync();}finally{await directory.close();}}finally{await fs.rm(tmp,{force:true}).catch(()=>undefined);}});this.queue=operation.catch(()=>undefined);return operation;}
}

function freshState(){const intents={};return{version:1,intents,checksum:stateChecksum(intents)};}
function verifyState(state){if(!state||state.version!==1||!state.intents||typeof state.intents!=='object'||Array.isArray(state.intents))throw intentError('SYNCIO_INTENT_LOG_CORRUPT','invalid intent log');const expected=stateChecksum(state.intents);if(state.checksum!==undefined&&state.checksum!==expected)throw intentError('SYNCIO_INTENT_LOG_CORRUPT','intent log checksum mismatch');state.checksum=expected;for(const intent of Object.values(state.intents))validatePersistedIntent(intent);}
function stateChecksum(intents){return crypto.createHash('sha256').update(stableStringify(intents)).digest('hex');}
function stableStringify(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stableStringify).join(',')}]`;return`{${Object.keys(value).sort().map((key)=>`${JSON.stringify(key)}:${stableStringify(value[key])}`).join(',')}}`;}
function normalizeMutations(intent){const values=intent.mutations??(intent.mutation?[intent.mutation]:null);if(!Array.isArray(values)||!values.length)throw new TypeError('intent mutations required');return values.map((mutation)=>{if(!mutation||typeof mutation!=='object'||typeof mutation.collection!=='string'||!mutation.collection)throw new TypeError('intent mutation collection required');if(!['put','insert','upsert','remove'].includes(mutation.type))throw new TypeError('unsupported intent mutation type');if(mutation.type==='remove'){if(typeof mutation.id!=='string'||!mutation.id)throw new TypeError('remove intent requires id');return{type:'remove',collection:mutation.collection,id:mutation.id};}if(!mutation.record||typeof mutation.record!=='object'||Array.isArray(mutation.record)||typeof mutation.record.id!=='string'||!mutation.record.id)throw new TypeError('write intent requires record id');return{type:mutation.type,collection:mutation.collection,record:clone(mutation.record)};});}
function normalizeRetry(value={}){const maxAttempts=value.maxAttempts??8;if(!Number.isSafeInteger(maxAttempts)||maxAttempts<1||maxAttempts>100)throw new TypeError('intent maxAttempts must be 1-100');return{maxAttempts};}
function validateIntent(intent){if(!intent||typeof intent!=='object'||Array.isArray(intent))throw new TypeError('intent object required');if(intent.intentId!==undefined&&(typeof intent.intentId!=='string'||!intent.intentId))throw new TypeError('intentId must be non-empty string');if(intent.expiresAt!==undefined&&intent.expiresAt!==null&&(!Number.isFinite(intent.expiresAt)||intent.expiresAt<=0))throw new TypeError('expiresAt must be positive timestamp');if(!['reject','overwrite'].includes(intent.conflictPolicy??'reject'))throw new TypeError('invalid conflictPolicy');normalizeMutations(intent);normalizeRetry(intent.retryPolicy);}
function validatePersistedIntent(intent){if(!intent||intent.version!==1||typeof intent.intentId!=='string'||!Array.isArray(intent.mutations)||typeof intent.status!=='string')throw intentError('SYNCIO_INTENT_LOG_CORRUPT','invalid persisted intent');}
function limit(message){const error=new Error(message);error.code='SYNCIO_RESOURCE_LIMIT';return error;}
function intentError(code,message){const error=new Error(message);error.code=code;return error;}
